# Generated by Django 3.2.25 on 2024-10-25 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20241025_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orignal_bag',
            new_name='original_bag',
        ),
    ]
